using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Eav.Models
{
    public abstract class DatabaseObject
    {
        protected DatabaseObject()
        {
            Id = Guid.NewGuid();
        }

        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public Guid Id { get; set; }

    }
}